### ISSUE TITLE
Not available for python 3.7

### ISSUE THREAD

**Issue by constantinpape** [conda-forge/skan-feedstock#12]
I would really like to use `skan`, but it is not available for python 3.7 (at least not on Linux).

```
constantin@AnnasAcerVN7:~$ conda create -n skan -c conda-forge skan python=3.7
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7
  - skan -> python=3.5 -> openssl=1.0.1
  - skan -> python=3.5 -> readline=6.2
  - skan -> python=3.5 -> tk=8.5
  - skan -> python=3.5 -> xz==5.0.5
Use "conda info <package>" to see the dependencies for each package.
```

Is there a specific reason for this?
Looking at the recipe I only found that builds are restricted to python >= 3.6:
https://github.com/conda-forge/skan-feedstock/blob/master/recipe/meta.yaml#L16

**Comment by jni** [comment]
Hi @constantinpape! See https://github.com/conda-forge/skan-feedstock/pull/11

Basically, mpl 3.0 broke the tests which means that the recipe won't build. I need to update mpl and/or make it an optional dependency, then do a patch release, but haven't found the time recently. 

Short term maybe you can install from pip? Or is that abhorrent to you? =P

**Comment by constantinpape** [comment]
I see.

> Short term maybe you can install from pip? Or is that abhorrent to you? =P

Barely acceptable :P. 
I did install it with pip now and that's fine for me for the time being.

Thanks for the quick reply :).

**Comment by k-dominik** [comment]
I think this can be closed :)
